### ISSUE TITLE
Request for one docker image for Pencil experiments

### ISSUE THREAD

**Issue by blossomin** [lightbulb128/Pencil#4] opened 2024-10-13 15:02 UTC
Hi, I found it's somehow hard to get every component work well for Pencil. 
I went through all the steps to run Pencil for nn1 on my test machine1, and everything was ready.
but I switched to another machine2 this week, and found the pytorch version(GPU kernel doesn't exist), libtroy.so have some issues, which confused me although I have already taken the suggested solution.

so I wonder whether it's possible to build a docker image from your side which can ease the development and reproduction.

**Comment by lightbulb128** [comment] 2024-10-16 10:22
Duplicate of #2

**Closed by lightbulb128** 2024-10-16 10:22 UTC
